spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://den1.mysql6.gear.host:3306/zetocrm?useSSL=false
    username: zetocrm
    password: Jx85Z_Wz_yBB
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true

